# This is a basic workflow to help you get started with Actions

name: Sync data weekly

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 9 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Sync data from fivetran to snowflake every sunday 
        run: |
          curl --location 'https://api.fivetran.com/v1/connectors/sans_night/sync' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic cEZQWnp1Z3dPWXJVM0FlbToxcmxpT0cwMnNMRTJEVmFoVDVjOGNraEVhdzFlcWY4RA==' \
          --header 'Cookie: INGRESSCOOKIE=0b3ca95d590c31dfda4517898ae984f8|bac6da9b4d464a443a3af1340233b03f' \
          --data '{
          "force": false
          }'
