name: "Sync partial weekly data"
on:
  schedule:
  - cron: "55 16 * * 0"
  workflow_dispatch:
jobs:
  run-updater:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Get current date
      id: todays-date
      run: echo "TODAYS_DATE=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
    - name: Fivetran update the pattern of Paycom Labor Report
      run: |
        import requests
        import json
        from datetime import datetime

        url = "https://api.fivetran.com/v1/connectors/raining_connection"

        current_date=datetime.today()
        formatted_date = current_date.strftime('%d%m%Y')
        pat="Sales"+formatted_date


        payload = json.dumps({
          "paused": "false",
          "pause_after_trial": "false",
          "sync_frequency": "360",
          "data_delay_threshold": "0",
          "data_delay_sensitivity": "NORMAL",
          "schedule_type": "manual",
          "is_historical_sync": "false",
          "config": {
          "pattern": pat
        }
        })
        headers = {
          'Content-Type': 'application/json',
          'Authorization': 'Basic cEZQWnp1Z3dPWXJVM0FlbToxcmxpT0cwMnNMRTJEVmFoVDVjOGNraEVhdzFlcWY4RA==',
          'Cookie': 'INGRESSCOOKIE=dd37844c17c95cfbdcffe420bc4920e6|bac6da9b4d464a443a3af1340233b03f'
        }

        response = requests.request("PATCH", url, headers=headers, data=payload)

        print(response.text)
